#!/bin/bash
# MCP Setup Script for Claude Code in Cursor
# This script helps you configure API tokens for GitHub, Supabase, and Vercel MCP servers

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   MCP Server Setup for Claude Code                        ║"
echo "║   GitHub + Supabase + Vercel Integration                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

MCP_ENV_FILE=".cursor/.env.mcp"
MCP_ENV_EXAMPLE=".cursor/.env.mcp.example"

# Check if example file exists
if [ ! -f "$MCP_ENV_EXAMPLE" ]; then
    echo -e "${RED}ERROR: $MCP_ENV_EXAMPLE not found${NC}"
    exit 1
fi

# Check if .env.mcp already exists
if [ -f "$MCP_ENV_FILE" ]; then
    echo -e "${YELLOW}⚠️  $MCP_ENV_FILE already exists${NC}"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
    cp "$MCP_ENV_FILE" "$MCP_ENV_FILE.backup"
    echo -e "${GREEN}✓${NC} Backup created: $MCP_ENV_FILE.backup"
fi

echo ""
echo "You'll need three API tokens. Press Enter after each token."
echo "Don't worry - these are stored locally and never committed to git."
echo ""

# GitHub Token
echo -e "${BLUE}1. GitHub Personal Access Token${NC}"
echo "   Get it from: https://github.com/settings/tokens"
echo "   Required scopes: repo, workflow, read:org"
echo ""
read -p "Enter your GitHub token: " GITHUB_TOKEN

# Supabase Project Ref
echo ""
echo -e "${BLUE}2. Supabase Project Reference ID${NC}"
echo "   Get it from: Supabase Dashboard → Settings → General"
echo "   Example format: kjfizpagyleefuucsdbu"
echo ""
read -p "Enter your Supabase project ref: " SUPABASE_REF

# Vercel Token
echo ""
echo -e "${BLUE}3. Vercel API Token${NC}"
echo "   Get it from: https://vercel.com/account/tokens"
echo ""
read -p "Enter your Vercel token: " VERCEL_TOKEN

# Validate inputs
if [ -z "$GITHUB_TOKEN" ] || [ -z "$SUPABASE_REF" ] || [ -z "$VERCEL_TOKEN" ]; then
    echo ""
    echo -e "${RED}ERROR: All three tokens are required${NC}"
    exit 1
fi

# Create .env.mcp file
cat > "$MCP_ENV_FILE" <<EOF
# MCP API Tokens Configuration
# Generated by setup-mcp.sh on $(date)

# GitHub Personal Access Token
GITHUB_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN

# Supabase Project Reference ID
SUPABASE_PROJECT_REF=$SUPABASE_REF

# Vercel API Token
VERCEL_API_TOKEN=$VERCEL_TOKEN
EOF

echo ""
echo -e "${GREEN}✓${NC} MCP tokens configured successfully!"
echo ""

# Install Vercel MCP dependencies if needed
if [ ! -d "mcp-servers/vercel/node_modules" ]; then
    echo -e "${YELLOW}Installing Vercel MCP server dependencies...${NC}"
    cd mcp-servers/vercel && npm install && cd ../..
    echo -e "${GREEN}✓${NC} Vercel MCP dependencies installed"
    echo ""
fi

echo "╔════════════════════════════════════════════════════════════╗"
echo "║                    Setup Complete! ✓                       ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Next steps:"
echo "  1. Restart Cursor IDE to load the MCP servers"
echo "  2. Open this project in Cursor"
echo "  3. Start chatting with Claude Code!"
echo ""
echo "Example commands you can try:"
echo "  • 'Show me all open pull requests'"
echo "  • 'What's the latest Vercel deployment status?'"
echo "  • 'Query the database schema in Supabase'"
echo ""
echo -e "${GREEN}Your tokens are stored in: $MCP_ENV_FILE${NC}"
echo -e "${YELLOW}This file is git-ignored and will NOT be committed.${NC}"
echo ""
